name: UniqueSkills
version: '${version}'
main: com.uniqueskills.UniqueSkillsPlugin
api-version: '1.20'
author: YourName
description: Unique Skills - Blink, Blast, and Teleport abilities

commands:
  blink:
    description: Toggle Blink ability
    usage: /blink
  blast:
    description: Toggle Blast ability
    usage: /blast
  teleport:
    description: Toggle Teleport ability
    usage: /teleport
  dash:
    description: Toggle Dash ability
    usage: /dash
  uskills:
    description: Open the main GUI to select and manage special abilities (Blink, Blast, Teleport, Dash).
    usage: /uskills
    aliases: [us]

permissions:
  valorantskills.use:
    description: Allows use of skills
    default: true
